'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
Public Module Resources
    
    Private resourceMan As Global.System.Resources.ResourceManager
    
    Private resourceCulture As Global.System.Globalization.CultureInfo
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CCN.UI.WinForms.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Public ReadOnly Property large_error() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("large_error", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property large_important() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("large_important", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property large_warning() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("large_warning", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_config() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_config", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_developer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_developer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_errors() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_errors", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_events() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_events", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_groups() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_groups", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_key() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_key", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_list() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_list", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_lists() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_lists", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_lock() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_lock", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_report() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_report", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_rights() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_rights", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_role() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_role", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_settings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_settings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_update() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_update", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_users() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_users", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property medium_warnings() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("medium_warnings", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_accept() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_accept", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_application_xml() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_application_xml", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_archives() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_archives", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_arrow_down() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_arrow_down", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_arrow_left() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_arrow_left", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_arrow_right() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_arrow_right", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_arrow_up() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_arrow_up", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_barcode() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_barcode", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_blocked() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_blocked", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_calculator() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_calculator", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_chart_line() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_chart_line", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_close() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_close", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_coins() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_coins", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_coins_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_coins_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_coins_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_coins_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_contact() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_contact", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_end_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_end_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_fastforward_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_fastforward_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_pause_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_pause_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_play_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_play_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_rewind_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_rewind_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_start_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_start_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_control_stop_blue() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_control_stop_blue", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_database_refresh() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_database_refresh", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_empty() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_empty", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_error() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_error", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_info() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_info", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_list() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_list", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_ok() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_ok", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_remove() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_remove", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_document_warning() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_document_warning", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_edit_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_edit_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_eye() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_eye", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_filter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_filter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_flip_horizontal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_flip_horizontal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_import() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_import", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_mail() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_mail", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_page() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_page", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folder_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folder_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folders() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folders", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_folders_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_folders_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_gear() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_gear", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_group_box() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_group_box", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_invoice() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_invoice", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_list() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_list", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_list_box() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_list_box", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_listbox() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_listbox", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_lock_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_lock_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_mail() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_mail", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_mail_copy() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_mail_copy", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_mail_minus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_mail_minus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_mail_pencil() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_mail_pencil", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_mail_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_mail_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_okay() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_okay", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_pill() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_pill", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_pill_arrow() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_pill_arrow", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_pill_minus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_pill_minus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_pill_plus() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_pill_plus", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_pill_search() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_pill_search", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_print() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_print", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_showhide() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_showhide", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_statistics() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_statistics", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_sum() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_sum", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_system_users() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_system_users", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_table_autosize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_table_autosize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_table_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_table_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_table_excel() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_table_excel", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_table_export() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_table_export", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_table_import() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_table_import", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_tabs() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_tabs", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_template() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_template", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_undo_start() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_undo_start", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_user() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_user", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_user_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_user_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_user_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_user_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_user_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_user_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users_add() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users_add", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users_delete() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users_delete", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users_edit() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users_edit", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users_go() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users_go", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_users_gray() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_users_gray", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_warning() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_warning", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Public ReadOnly Property small_wrench() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("small_wrench", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Module
